src/Entity/Forecast.php
<?php

namespace App\Entity;

use App\Repository\ForecastRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Ignore;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: ForecastRepository::class)]
class Forecast
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups('api')]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups('api')]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    #[Groups('api')]
    private ?int $temperatureCelsius = null;

    #[ORM\Column]
    #[Groups('api')]
    private ?int $flTemperatureCelsius = null;

    #[ORM\Column(nullable: true)]
    #[Groups('api')]
    private ?int $pressure = null;

    #[ORM\Column(nullable: true)]
    #[Groups('api')]
    private ?int $humidity = null;

    #[ORM\Column(nullable: true)]
    #[Groups('api')]
    private ?float $windSpeed = null;

    #[ORM\Column(nullable: true)]
    #[Groups('api')]
    private ?int $windDeg = null;

    #[ORM\Column(nullable: true)]
    #[Groups('api')]
    private ?int $cloudiness = null;

    #[ORM\Column(length: 255)]
    #[Groups('api')]
    private ?string $icon = null;

    #[ORM\ManyToOne(inversedBy: 'forecasts')]
    #[ORM\JoinColumn(nullable: false)]
    #[Ignore]
    private ?Location $location = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getTemperatureCelsius(): ?int
    {
        return $this->temperatureCelsius;
    }

    public function setTemperatureCelsius(int $temperatureCelsius): static
    {
        $this->temperatureCelsius = $temperatureCelsius;

        return $this;
    }

    public function getTemperatureFarenheit(): ?int
    {
        return round(($this->getTemperatureCelsius() * 9 / 5) + 32);
    }

    public function getFlTemperatureCelsius(): ?int
    {
        return $this->flTemperatureCelsius;
    }

  
    public function setFlTemperatureCelsius(int $flTemperatureCelsius): static
    {
        $this->flTemperatureCelsius = $flTemperatureCelsius;

        return $this;
    }

    public function getFlTemperatureFahrenheit(): ?int
    {
        return round(($this->getFlTemperatureCelsius() * 9 / 5) + 32);
    }

    public function getPressure(): ?int
    {
        return $this->pressure;
    }

    public function setPressure(?int $pressure): static
    {
        $this->pressure = $pressure;

        return $this;
    }

    public function getHumidity(): ?int
    {
        return $this->humidity;
    }

    public function setHumidity(?int $humidity): static
    {
        $this->humidity = $humidity;

        return $this;
    }

    public function getWindSpeed(): ?float
    {
        return $this->windSpeed;
    }

    public function setWindSpeed(?float $windSpeed): static
    {
        $this->windSpeed = $windSpeed;

        return $this;
    }

    public function getWindDeg(): ?int
    {
        return $this->windDeg;
    }

    public function setWindDeg(?int $windDeg): static
    {
        $this->windDeg = $windDeg;

        return $this;
    }

    public function getCloudiness(): ?int
    {
        return $this->cloudiness;
    }

    public function setCloudiness(?int $cloudiness): static
    {
        $this->cloudiness = $cloudiness;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(string $icon): static
    {
        $this->icon = $icon;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }
}

src/Controller/WeatherController.php
<?php

namespace App\Controller;

use App\Entity\Location;
use App\Repository\ForecastRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('weather')]
class WeatherController extends AbstractController
{
    #[Route('/{countryCode}/{cityName}' , 'app_weather_forecast')]
    public function forecast(
        Location $location,
        ForecastRepository $repository,
        string $countryCode, 
        string $cityName
    ): Response
    {
        if($location)
        {
            $forecasts = $repository->getLocationForecasts($location->getId());

            // $forecasts = [
            //     [
            //         "date" => new \DateTime('2024-01-01'),
            //         "temperatureCelsius" => 17,
            //         "flTemperatureCelsius" => 16,
            //         "pressure" => 1000,
            //         "humidity" => 64,
            //         "wind_speed" => 3.2,
            //         "wind_deg" => 270,
            //         "cloudiness" => 75,
            //         'icon' => 'sun',
            //     ],
            //     [
            //         "date" => new \DateTime('2024-01-02'),
            //         "temperatureCelsius" => 12,
            //         "flTemperatureCelsius" => 13,
            //         "pressure" => 1001,
            //         "humidity" => 62,
            //         "wind_speed" => 2.2,
            //         "wind_deg" => 180,
            //         "cloudiness" => 50,
            //         'icon' => 'cloud',
            //     ],
            //     [
            //         "date" => new \DateTime('2024-01-03'),
            //         "temperatureCelsius" => 11,
            //         "flTemperatureCelsius" => 12,
            //         "pressure" => 1010,
            //         "humidity" => 63,
            //         "wind_speed" => 3.5,
            //         "wind_deg" => 270,
            //         "cloudiness" => 15,
            //         'icon' => 'cloud-rain',
            //     ],
            // ];

            return $this->render('weather/forecast.html.twig',[
                'location' => $location,
                'forecasts' => $forecasts,
                'countryCode' => $countryCode,
                'city' => $cityName
            ]);
        } else {
            return $this->createNotFoundException();
        }
    }
}

templates/weather/forecast.html.twig
{% extends 'layout_boxed.html.twig' %}

{% block title %}
    Weather Forecaster for {{ city }}, {{ countryCode }}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col col-12">
			<h3>Forecast for
				{{ city }},
				{{ countryCode }}
			</h3>
		</div>
	</div>
	<div class="row">
		<div class="col col-12">
			<div id="map" style="height:400px;"></div>
		</div>
	</div>

	<div class="row">
		{% for forecast in forecasts %}
			<div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 mt-1">
				<div class="card">
					<div class="card-body">
						<div class="row">
							<div class="col col-6 card-title">{{ forecast.date | date('l') }}</div>
							<div class="col col-6 card-title text-end">{{ forecast.date | date('m.y') }}</div>
						</div>
						<div class="row">
							<div class="col col-6 card-title text-center">
								<h1>
									<i class="bi bi-{{ forecast.icon }} align-middle"></i>
								</h1>
							</div>
							<div class="col col-6 card-title">
								<h3>
									<b>{{ forecast.temperatureCelsius }}
										&deg;</b>
								</h3>
								<em>Feels like
									{{ forecast.flTemperatureCelsius }}&deg;</em>
							</div>
						</div>

						<div class="row">
							<div class="col col-6 card-title">
								<b>Pressure</b>
							</div>
							<div class="col col-6 card-title">{{ forecast.pressure }}</div>
						</div>
						<div class="row">
							<div class="col col-6 card-title">
								<b>Humidity</b>
							</div>
							<div class="col col-6 card-title">{{ forecast.humidity }}%</div>
						</div>
						<div class="row">
							<div class="col col-6 card-title">
								<b>Wind</b>
							</div>
							<div class="col col-6 card-title">{{ forecast.windDeg }}m/s</div>
						</div>
						<div class="row">
							<div class="col col-6 card-title">
								<b>Cloudiness</b>
							</div>
							<div class="col col-6 card-title">{{ forecast.cloudiness }}%</div>
						</div>
						<div class="row">
							<div class="col col-6 card-title">
								<b>Farenheit</b>
							</div>
							<div class="col col-6 card-title">{{ forecast.temperatureFarenheit }}&deg;F</div>
						</div>
						<div class="row">
							<div class="col col-6 card-title">
								<b>Feels like </b>
							</div>
							<div class="col col-6 card-title">{{ forecast.FlTemperatureFahrenheit }}&deg;F</div>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>

    <script>
        var map = L.map('map').setView([{{location.latitude}}, {{location.longitude}}], 13);
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);
        var marker = L.marker([{{location.latitude}}, {{location.longitude}}]).addTo(map);
    </script>
{% endblock %}